# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sales_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=20)),
                ('booking_price', models.IntegerField()),
                ('streaming_numbers', models.IntegerField()),
                ('albums', models.ManyToManyField(to='mypage.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_title', models.CharField(max_length=50)),
                ('attendance', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('status', models.CharField(choices=[(('booked',), 'booked'), (('contacted',), 'contacted'), ('paid', 'paid')], default='contacted', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone_number', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('manager', 'manager'), ('organizer', 'organizer'), ('rigger', 'rigger'), ('chief organizer', 'chief organizer'), ('volunteer', 'volunteer')], default='volunteer', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('scene_name', models.CharField(choices=[(('storsalen',), 'storsalen'), (('klubben',), 'klubben'), (('knaus',), 'knaus')], default='storsalen', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='personnel',
            field=models.ManyToManyField(to='mypage.Person'),
        ),
        migrations.AddField(
            model_name='band',
            name='prior_concerts',
            field=models.ManyToManyField(to='mypage.Concert'),
        ),
    ]
