# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[(0, 'booked'), (1, 'contacted'), (2, 'paid')], default='contacted', max_length=20),
        ),
    ]
