# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20160915_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'booked'), ('CONTACTED', 'contacted'), ('PAID', 'paid')], default='contacted', max_length=20),
        ),
    ]
