# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20160915_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'manager'), ('ORGANIZER', 'organizer'), ('RIGGER', 'rigger'), ('CHIEF_ORGANIZER', 'chief organizer'), ('VOLUNTEER', 'volunteer')], default='volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_name',
            field=models.CharField(choices=[('STORSALEN', 'storsalen'), ('KLUBBEN', 'klubben'), ('KNAUS', 'knaus')], default='storsalen', max_length=20),
        ),
    ]
