# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_concert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='scene',
            field=models.OneToOneField(default=(('STORSALEN', 'storsalen'), ('KLUBBEN', 'klubben'), ('KNAUS', 'knaus')), on_delete=django.db.models.deletion.CASCADE, to='mypage.Scene'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CONTACTED', 'Contacted'), ('PAID', 'Paid')], default='contacted', max_length=20),
        ),
    ]
