# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_auto_20160915_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='prior_concerts',
        ),
        migrations.AddField(
            model_name='concert',
            name='band',
            field=models.OneToOneField(default='Placeholder', on_delete=django.db.models.deletion.CASCADE, to='mypage.Band'),
        ),
    ]
