# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_auto_20160915_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='band',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mypage.Band'),
        ),
    ]
