# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0010_remove_concert_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='scene',
        ),
    ]
