# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0014_auto_20160915_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='id',
        ),
        migrations.AlterField(
            model_name='concert',
            name='band',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mypage.Band'),
        ),
    ]
