# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sales_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=20)),
                ('booking_price', models.IntegerField()),
                ('streaming_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('attendance', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Contacted'), ('P', 'Paid')], max_length=1)),
                ('bands', models.ManyToManyField(to='band_booking.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('M', 'manager'), ('O', 'organizer'), ('R', 'rigger'), ('C', 'chief organizer'), ('V', 'volunteer')], default='V', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('handicap_accessible', models.BooleanField()),
                ('scene_name', models.CharField(choices=[('Storsalen', 'storsalen'), ('Klubben', 'klubben'), ('Knaus', 'knaus'), ('Edgar', 'edgar')], default='Storsalen', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='personnel',
            field=models.ManyToManyField(to='band_booking.Person'),
        ),
        migrations.AddField(
            model_name='concert',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='band_booking.Scene'),
        ),
        migrations.AddField(
            model_name='band',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='band_booking.Person'),
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='band_booking.Band'),
        ),
    ]
