# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_member',
            field=models.ManyToManyField(related_name='band_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
