# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='band',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
