# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='handicap_accessible',
            field=models.NullBooleanField(),
        ),
    ]
