# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_booking', '0002_auto_20161026_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technical_needs',
            old_name='Equipment_name',
            new_name='equipment_name',
        ),
        migrations.AlterField(
            model_name='band',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
