# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_booking', '0003_auto_20161019_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
