# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band_booking', '0004_auto_20161019_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_member',
            field=models.ManyToManyField(related_name='band_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='band',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
