# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('band_booking', '0004_auto_20161019_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_needs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_name', models.CharField(default=' ', max_length=128)),
                ('amount', models.IntegerField(default=1)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band_booking.Band')),
            ],
        ),
    ]
