# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band_booking', '0005_technical_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
