# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band_booking', '0006_band_band_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='band_member',
        ),
        migrations.AddField(
            model_name='band',
            name='band_member',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
